### ISSUE TITLE
issue_1

### ISSUE THREAD

**Issue by udawe78** [AviArta/cheaptrip_training#2]
Отлично! Скрипт отработал, try-except - это тоже здорово. Давай оптимизируем еще немного, учитывая следующее:
1) твой скрипт будет обрабатывать только файлы *.json, поэтому для их чтения и записи давай сразу использовать соответствующие методы из модуля json. Например, читать файл сразу в словарь (dictionary).
2) ключи в словаре менять не нужно, только значения, и желательно это делать за один "пробег"/цикл, а не за два
3) не критично, но для работы с файлами и папками вместо модуля os предпочтительней использовать модуль pathlib, в частности его класс Path

**Comment by AviArta** [comment]
Замечания устранены.
